version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: newdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: coinsdatabase
    volumes:
     - pg-data:/var/lib/postgresql/data
     - ./internal/adapters/storage/migrations/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: my-app
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: coinsdatabase
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8080:8080"
volumes:
  pg-data: