name: Build, Lint and Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.6' 

      - name: Install Dependencies
        run: go mod download

      - name: Run Linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run

      - name: Build Application
        run: go build -o app ./cmd/app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: app